package com.example.passfashion.dto.Response;

import java.util.ArrayList;
import java.util.List;

import com.example.passfashion.model.Product;
import com.fasterxml.jackson.annotation.JsonInclude;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class WishlistResponse {
  private long id;
  private String name;
  private double price;
  private String categoryName;
  private String imageUrl;
  private int qty;
  private String description;
  private List<String> imageUrls = new ArrayList<>();

  // constructor for map to wishlist response from product
  public WishlistResponse(Product product) {
    this.id = product.getId();
    this.name = product.getName();
    this.price = product.getPrice();
    this.categoryName = product.getCategory() != null ? product.getCategory().getLink() : null;
    this.imageUrl = product.getImages() != null && !product.getImages().isEmpty() ? product.getImages().get(0).getUrl()
        : null;
    this.qty = product.getQty();
    this.description = product.getDescription();

    if (product.getImages() != null) {
      product.getImages().forEach(image -> this.imageUrls.add(image.getUrl()));
    }
  }

  // getter and setter methods are generated by Lombok's @Data annotation
  public long getId() {
    return id;
  }
  public void setId(long id) {
    this.id = id;
  }
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  

}
